/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://zbzwj3wuojex7lxemlfp6nbmxy.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-cflywgq7yjd6bmjt22lezhqypm",
    "aws_cognito_identity_pool_id": "eu-north-1:e3f3fe8d-beeb-4408-8f36-9e29ffd11641",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_0lhGMnnfN",
    "aws_user_pools_web_client_id": "3bolacrqpjks7sf8rhrga527oe",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "yelp3-20230405203732-hostingbucket-main",
    "aws_content_delivery_bucket_region": "eu-north-1",
    "aws_content_delivery_url": "http://yelp3-20230405203732-hostingbucket-main.s3-website.eu-north-1.amazonaws.com"
};


export default awsmobile;
